server:
  port: 3001
spring:
  application:
    name: demo-service-ribbon-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
  instance: 
    prefer-ip-address: true
management:
  security: 
    enabled: false