server:
  port: 2001
spring:
  application:
    name: demo-service-provider-a
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
  instance:
    prefer-ip-address: true
management:
  security: 
    enabled: false
